variables:
    GIT_CLONE_PATH: $CI_BUILDS_DIR/$CI_PROJECT_NAME/$CI_COMMIT_REF_NAME
    GIT_STRATEGY: 'fetch'
    GIT_CHECKOUT: 'true'
    GIT_CLEAN_FLAGS: 'none'
    GIT_DEPTH: 0

stages:
    - deploy

deploy-staging:
    stage: deploy
    variables:
        CI_ENVIRONMENT_DOMAIN: $CI_PROJECT_NAME.creonit.dev
        APP_DEBUG: 1
    environment:
        name: staging
        url: https://$CI_PROJECT_NAME.creonit.dev
    script:
        - app/stage/build
    rules:
        - if: $CI_COMMIT_BRANCH == "master"
          when: always
          
develop-staging:
    stage: deploy
    variables:
        CI_ENVIRONMENT_DOMAIN: $CI_PROJECT_NAME-$CI_COMMIT_BRANCH.creonit.dev
        APP_DEBUG: 1
    environment:
        name: staging
        url: https://$CI_PROJECT_NAME-$CI_COMMIT_BRANCH.creonit.dev
    script:
        - app/stage/build
    rules:
        - if: $CI_COMMIT_BRANCH == "develop"
          when: always
