version: '3.4'

services:
  app:
    build:
      context: .
      target: dev
    command: uvicorn src.main:app --reload --proxy-headers --host 0.0.0.0 --port 8000
    ports:
      - "8000:8000"

  db:
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      - "POSTGRES_DB=postgres"
      - "POSTGRES_USER=postgres"
      - "POSTGRES_PASSWORD=postgres"
    ports:
      - "5432:5432"

  redis:
    volumes:
      - redis-data:/data

  worker:
    build:
      context: .
      target: dev

volumes:
  db-data:
  redis-data:
