version: '3.4'

x-app: &app
  build:
    context: .
    target: base
  working_dir: /app
  depends_on:
    - db
    - redis
  env_file:
    - .env
  volumes:
    - ./:/app
  logging:
    options:
      max-size: "50m"

services:
  app:
    <<: *app

  db:
    image: postgres:15.4

  redis:
    image: redis:7.2
    command: redis-server --appendonly yes

  worker:
    <<: *app
    depends_on:
      - app
    command: rq worker --with-scheduler -c src.config.redis
