version: '3.4'

services:
  app:
    build:
      context: .
      target: stage
    entrypoint: ./entrypoint.sh
    restart: unless-stopped
    command: uvicorn src.main:app --proxy-headers --host 0.0.0.0 --port 80
    ulimits:
      core: 0
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.${CI_PROJECT_NAME}-${CI_COMMIT_BRANCH}.rule=Host(`${CI_ENVIRONMENT_DOMAIN}`)"
      - "traefik.http.routers.${CI_PROJECT_NAME}-${CI_COMMIT_BRANCH}.tls.certresolver=default"

  db:
    restart: unless-stopped
    volumes:
      - /var/www/storage/${CI_PROJECT_NAME}-${CI_COMMIT_BRANCH}/postgres:/var/lib/postgresql/data
    environment:
      - "POSTGRES_DB=${DB_NAME}"
      - "POSTGRES_USER=${DB_USER}"
      - "POSTGRES_PASSWORD=${DB_PASSWORD}"
