"""add_path_field_to_gitlab_project

Revision ID: 1533d2a7d676
Revises: 98fd171f2f3d
Create Date: 2023-08-10 12:05:14.823913

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1533d2a7d676'
down_revision = '98fd171f2f3d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('gitlab_project', sa.Column('path_with_namespace', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('gitlab_project', 'path_with_namespace')
    # ### end Alembic commands ###
