"""add table mattermost channel

Revision ID: f6f1bd85935d
Revises: c40ee8c0eabb
Create Date: 2023-08-07 11:39:40.175667

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f6f1bd85935d'
down_revision = 'c40ee8c0eabb'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mattermost_channel',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('mattermost_channel')
    # ### end Alembic commands ###
