"""add__avatar_url_field__gitlab_project

Revision ID: 13488ed98462
Revises: dccf1cbf8997
Create Date: 2023-08-14 08:10:47.319721

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '13488ed98462'
down_revision = 'dccf1cbf8997'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('gitlab_project', sa.Column('avatar_url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('gitlab_project', 'avatar_url')
    # ### end Alembic commands ###
