"""add__return_mm_channel

Revision ID: 16a24b7389c9
Revises: b089de9f3c7c
Create Date: 2023-08-14 10:24:12.167938

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '16a24b7389c9'
down_revision = 'b089de9f3c7c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mattermost_channel',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('iid', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('display_name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('gitlab_project_mattermost_channel',
    sa.Column('gitlab_project_id', sa.Integer(), nullable=False),
    sa.Column('mattermost_channel_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['gitlab_project_id'], ['gitlab_project.id'], ),
    sa.ForeignKeyConstraint(['mattermost_channel_id'], ['mattermost_channel.id'], ),
    sa.PrimaryKeyConstraint('gitlab_project_id', 'mattermost_channel_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('gitlab_project_mattermost_channel')
    op.drop_table('mattermost_channel')
    # ### end Alembic commands ###
