"""delete__temp_remove_mm_channel

Revision ID: b089de9f3c7c
Revises: 13488ed98462
Create Date: 2023-08-14 10:22:56.228152

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b089de9f3c7c'
down_revision = '13488ed98462'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('gitlab_project_mattermost_channel')
    op.drop_table('mattermost_channel')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mattermost_channel',
    sa.Column('id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='mattermost_channel_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('gitlab_project_mattermost_channel',
    sa.Column('gitlab_project_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('mattermost_channel_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['gitlab_project_id'], ['gitlab_project.id'], name='gitlab_project_mattermost_channel_gitlab_project_id_fkey'),
    sa.ForeignKeyConstraint(['mattermost_channel_id'], ['mattermost_channel.id'], name='gitlab_project_mattermost_channel_mattermost_channel_id_fkey'),
    sa.PrimaryKeyConstraint('gitlab_project_id', 'mattermost_channel_id', name='gitlab_project_mattermost_channel_pkey')
    )
    # ### end Alembic commands ###
