"""rename_url_field_gitlab_project

Revision ID: dccf1cbf8997
Revises: 1533d2a7d676
Create Date: 2023-08-11 13:51:31.050308

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dccf1cbf8997'
down_revision = '1533d2a7d676'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('ALTER TABLE gitlab_project RENAME COLUMN url TO web_url;')
    op.execute('ALTER INDEX ix_gitlab_project_url RENAME TO ix_gitlab_project_web_url;')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('ALTER TABLE gitlab_project RENAME COLUMN web_url TO url;')
    op.execute('ALTER INDEX ix_gitlab_project_web_url RENAME TO ix_gitlab_project_url;')
    # ### end Alembic commands ###
